//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doanh2026.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyHoatDong
    {
        public int MaNhatKy { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public string HanhDong { get; set; }
        public string BangTacDong { get; set; }
        public Nullable<int> MaBanGhi { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
